export const GET_TODO_REQUEST = 'GET_TODO_REQUEST'
export const GET_TODO_COMPLETE = 'GET_TODO_COMPLETE'

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_COMPLETE = 'ADD_TODO_COMPLETE'

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_COMPLETE = 'DELETE_TODO_COMPLETE'

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'
export const UPDATE_TODO_COMPLETE = 'UPDATE_TODO_COMPLETE'

export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const REQUEST_ERROR = 'REQUEST_ERROR'
export const SENDING_REQUEST = 'SENDING_REQUEST'
